[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mOutput "kubernetes_cluster_kubeconfig" not found[0m
[31m│[0m [0m
[31m│[0m [0m[0mThe output variable requested could not be found in the state file. If you
[31m│[0m [0mrecently added this to your configuration, be sure to run `terraform
[31m│[0m [0mapply`, since the state won't be updated with new output variables until
[31m│[0m [0mthat command is run.
[31m╵[0m[0m
