apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: github-api-dev
spec:
  type: ClusterIP
  selector:
    app: postgres-exporter
  ports:
    - port: 9187
      targetPort: 9187
      name: metrics

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: github-api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:latest
          ports:
            - containerPort: 9187
              name: metrics
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://postgres:$(DB_PASSWORD)@postgres:5432/github_repos?sslmode=disable"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "50m"
              memory: "64Mi"
