apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: github-api-ingress-docs
  namespace: github-api-dev
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/priority: "100"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # Docs - rewrite /docs/* to /* (VitePress serves at root with base: '/docs/')
          - path: /docs(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: docs
                port:
                  number: 5173
